version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/gestion_tickets
  mongo:
    image: mongo:6.0.39
    ports:
      - '27017:27017'
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend